### PR TITLE
Enhancements to `list-app`

### PR DESCRIPTION
**Pull request by AMoo-Miki**
Allow choosing IP for `list-app` #14 
Allow choosing port for certificate download in `list-app`
Catch illegal parameters passed to `list-app`

### CODE REVIEW

**Comment by codetheweb** [comment]
Looks pretty good, thank you for contributing.

Why did you remove the `address` dependency?  I know it's an extra dependency and something that's not too difficult to replicate, but I'd rather keep it for cleaner code and to eliminate any platform-specific edge cases that they've already thought of (plus, it's just 996 bytes gzipped).

Being able to show the number of available IPs is nice but not necessary in my mind.

**Comment by AMoo-Miki** [comment]
My pleasure.

I tried using `address` but it can't return all the IP addresses; it returns all the IPs for a single interface, but we need all the IP addresses on all interfaces. We also need the details of the IPs to exclude the ones marked `internal`. The list of the IPs is mainly used to validate the requested IP; I just noticed that I am not throwing an error for an invalid requested IP which I will add in a min.

**Comment by codetheweb** [comment]
Got it, that makes sense.

I'm going to just clean it up a bit and then it should be ready to merge.

**Comment by codetheweb** [comment]
Published in v1.8.3.

**Pull request merged**
