### PR TITLE
Use protocol version 3.3

### PR DESCRIPTION
**Pull request by XMB5**
Not sure if this is backwards compatible but it works for me

### CODE REVIEW

**Comment by codetheweb** [comment]
This doesn't work for me with my older plugs; can you please modify this so the protocol version can be specified with a flag?

I'll be happy to merge it in then; but it needs to be backwards-compatible.

**Comment by codetheweb** [comment]
Hey @XMB5 any update?  If you're not able to fix it I can take a look this weekend.

**Comment by XMB5** [comment]
I'm working on it, I'll push it in a few hours

**Comment by codetheweb** [comment]
Looks good, thanks for those changes 👍.

Merging now.

**Comment by codetheweb** [comment]
Published in v1.7.0.

**Pull request merged**
