### PR TITLE
Added support for Feit Wifi Lightbulbs

### PR DESCRIPTION
**Pull request by rrgeorge**
I've made some slight modifications the cli to detect the settings for the Feit Wifi Lightbulbs that can be purchased at Costco

### CODE REVIEW

**Comment by codetheweb** [comment]
👍 thank you.  This may fix issues for other people as well (https://github.com/codetheweb/tuyapi/issues/111).

**Comment by codetheweb** [comment]
Published in v1.4.4.

**Comment by rrgeorge** [comment]
I actually discovered that this doesn’t quite work right. It only finds the first bulb in the app. I have since reworked my changes and will submit a new pull request in a bit.

**Comment by codetheweb** [comment]
Ok

**Pull request merged**
